# cluster node conf
cluster.name: my-cluster
node.name: main-node

# data and logs
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

# network
network.host: 0.0.0.0
http.port: 9200

# Disable security features
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Disable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: false
# keystore.path: certs/http.p12

# Disable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: false
#  verification_mode: certificate
#  keystore.path: certs/transport.p12
#  truststore.path: certs/transport.p12

# Create a new cluster with the current node only
# Additional nodes can still join the cluster later
cluster.initial_master_nodes: 
  - "main-node"

# Allow HTTP API connections from anywhere
# Connections are encrypted and require user authentication
http.host: 0.0.0.0
